# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wb6d_cbTbFztz9Ose9ILstHgcXhdn3Vc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from datetime import datetime

# Install Kaggle CLI
!pip install -q kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d fengzhujoey/douban-datasetratingreviewside-information -p /content
!unzip -q /content/douban-datasetratingreviewside-information.zip -d /content/douban

# Use --no-check-certificate to ignore the expired SSL certificate
!wget --no-check-certificate https://files.grouplens.org/datasets/movielens/ml-1m.zip -O /content/ml-1m.zip

# This command should now work since the file will be downloaded correctly
!unzip -q /content/ml-1m.zip -d /content/movielens

!wget https://files.grouplens.org/datasets/movielens/ml-1m.zip -O /content/ml-1m.zip
!unzip -q /content/ml-1m.zip -d /content/movielens



# MovieLens 1M - Ratings
ml_ratings = pd.read_csv('/content/movielens/ml-1m/ratings.dat', sep='::', engine='python',
                         names=['UserID', 'MovieID', 'Rating', 'Timestamp'])
ml_ratings['Timestamp'] = pd.to_datetime(ml_ratings['Timestamp'], unit='s')
ml_ratings.head()

# List files inside the douban folder
os.listdir('/content/douban')

os.listdir('/content/douban/douban_dataset(text information)')

# Load movie interactions
df_movies = pd.read_csv('/content/douban/douban_dataset(text information)/movies_cleaned.txt', sep='\t', engine='python')

# Preview the data
df_movies.head()

df_users = pd.read_csv('/content/douban/douban_dataset(text information)/users_cleaned.txt', sep='\t', engine='python')
df_users.head()

!wget https://files.grouplens.org/datasets/movielens/ml-1m.zip -O ml-1m.zip
!unzip -q ml-1m.zip -d ml-1m

MOVIELENS_PATH = "/content/movielens/ml-1m/ratings.dat"
DOUBAN_MOVIE_PATH = "/content/douban/douban_dataset(text information)/movies_cleaned.txt"
DOUBAN_USERS_PATH = "/content/douban/douban_dataset(text information)/users_cleaned.txt"

print("\nLoading MovieLens 1M Ratings...")
movielens_df = pd.read_csv(MOVIELENS_PATH, sep='::', engine='python',
                           names=['UserID', 'MovieID', 'Rating', 'Timestamp'])

# Convert timestamp
movielens_df['Timestamp'] = pd.to_datetime(movielens_df['Timestamp'], unit='s')

# Sort by user and timestamp (for sequential modeling)
movielens_df = movielens_df.sort_values(['UserID', 'Timestamp'])

print("MovieLens Loaded ✅")
print(movielens_df.head())

print("\nLoading Douban Movie Ratings...")
douban_df = pd.read_csv(
    DOUBAN_MOVIE_PATH,
    sep='\t',
    engine='python',
    quoting=3,
    header=None,
    on_bad_lines='skip'  # ✅ skip malformed rows
)

# Truncate to first 4 columns
douban_df = douban_df.iloc[:, :4]
douban_df.columns = ['UserID', 'ItemID', 'Rating', 'Timestamp']

# Convert timestamp
douban_df['Timestamp'] = pd.to_datetime(douban_df['Timestamp'], unit='s', errors='coerce')

# Sort by user and time
douban_df = douban_df.sort_values(['UserID', 'Timestamp'])

print("Douban Movie Ratings Loaded ✅")
print(douban_df.head())

def simulate_sessions_fast(df, user_col='UserID', time_col='Timestamp', gap_minutes=30):
    df = df.copy()
    df.sort_values(by=[user_col, time_col], inplace=True)

    # Calculate time difference (in minutes) per user
    df['TimeDiff'] = df.groupby(user_col)[time_col].diff().dt.total_seconds().div(60)

    # New session if gap > threshold or NaN (first interaction)
    df['NewSession'] = (df['TimeDiff'].isna()) | (df['TimeDiff'] > gap_minutes)

    # Cumulative sum of new sessions per user
    df['SessionID'] = df.groupby(user_col)['NewSession'].cumsum()

    # Drop helper columns
    df.drop(columns=['TimeDiff', 'NewSession'], inplace=True)

    return df

movielens_df = simulate_sessions_fast(movielens_df)
douban_df = simulate_sessions_fast(douban_df)

movielens_df.to_csv("/content/movielens_preprocessed.csv", index=False)
douban_df.to_csv("/content/douban_preprocessed.csv", index=False)

print("\n✅ All Done: Preprocessed files saved for model training.")



"""##Data Visulaization"""

sns.set(style="whitegrid")
sns.set_palette("Set2")

print("\nGenerating Aesthetic Visualizations 📊")

# 1. Ratings Distribution (Fixed Douban)
douban_df['Rating'] = pd.to_numeric(douban_df['Rating'], errors='coerce')  # ✅ Fix here
douban_filtered = douban_df[douban_df['Rating'].between(0, 5)]
douban_filtered['Rating'] = douban_filtered['Rating'].round(1).astype(str)

plt.figure(figsize=(8, 5))
sns.countplot(data=movielens_df, x='Rating', palette='Set2')
plt.title("MovieLens Ratings Distribution")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# Douban Ratings Distribution
plt.figure(figsize=(8, 5))
sns.countplot(data=douban_df, x='Rating', palette='Set2')
plt.title("Douban Ratings Distribution")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# -- Convert Ratings --
douban_df['Rating'] = pd.to_numeric(douban_df['Rating'], errors='coerce')
douban_filtered = douban_df[douban_df['Rating'].between(0, 5)]
douban_filtered['Rating'] = douban_filtered['Rating'].round(1).astype(str)

# -- Pie Chart of Rating Distribution --
rating_counts = movielens_df['Rating'].value_counts().sort_index()
plt.figure(figsize=(6, 6))
plt.pie(rating_counts, labels=rating_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('Set3'))
plt.title("📊 MovieLens Ratings Proportion")
plt.tight_layout()
plt.show()

# -- Top 10 Most Active Users --
top_users = movielens_df['UserID'].value_counts().head(10)
plt.figure(figsize=(8, 5))
sns.barplot(x=top_users.index.astype(str), y=top_users.values, palette='coolwarm')
plt.title("🔥 Top 10 Most Active Users (MovieLens)")
plt.xlabel("User ID")
plt.ylabel("Number of Ratings")
plt.tight_layout()
plt.show()

# -- Rating vs Time Heatmap (MovieLens) --
movielens_df['Date'] = movielens_df['Timestamp'].dt.date
heatmap_data = movielens_df.groupby(['Date', 'Rating']).size().unstack().fillna(0)

plt.figure(figsize=(12, 6))
sns.heatmap(heatmap_data.T, cmap='YlGnBu', cbar_kws={'label': 'Interactions'})
plt.title("⏳ Rating Heatmap over Time (MovieLens)")
plt.xlabel("Date")
plt.ylabel("Rating")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
correlation = movielens_df[['UserID', 'MovieID', 'Rating', 'SessionID']].corr()
sns.heatmap(correlation, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("🧭 Feature Correlation Heatmap (MovieLens)")
plt.tight_layout()
plt.show()

# Choose a sample user
sample_user = movielens_df['UserID'].value_counts().index[0]
user_data = movielens_df[movielens_df['UserID'] == sample_user].sort_values('Timestamp')

plt.figure(figsize=(12, 2))
plt.plot(user_data['Timestamp'], user_data['MovieID'], marker='o', linestyle='-', color='#7570b3')
plt.title(f"🎞️ Item Interaction Path for User {sample_user}")
plt.xlabel("Timestamp")
plt.ylabel("Movie ID")
plt.tight_layout()
plt.show()

"""Sequence Transition Graph"""

import networkx as nx

# Create transition matrix (MovieLens)
sequence_df = movielens_df.sort_values(['UserID', 'Timestamp'])
transitions = {}

for _, group in sequence_df.groupby('UserID'):
    ratings = group['Rating'].tolist()
    for i in range(len(ratings)-1):
        pair = (ratings[i], ratings[i+1])
        transitions[pair] = transitions.get(pair, 0) + 1

# Create directed graph
G = nx.DiGraph()
for (src, dst), weight in transitions.items():
    G.add_edge(src, dst, weight=weight)

plt.figure(figsize=(10, 7))
pos = nx.spring_layout(G, seed=42)
edges = G.edges()
weights = [G[u][v]['weight'] for u,v in edges]
nx.draw(G, pos, with_labels=True, node_color='#ccebc5', edge_color='#2b8cbe', width=[w/50 for w in weights],
        node_size=2000, arrows=True, font_size=14, font_weight='bold')
plt.title("📈 Rating-to-Rating Transition Graph (MovieLens)")
plt.tight_layout()
plt.show()

"""Clustering Visualization"""

# Sample a few sessions from MovieLens
sample_sessions = movielens_df['SessionID'].dropna().unique()[:5]  # first 5 sessions

plt.figure(figsize=(10, 6))

for session_id in sample_sessions:
    session_data = movielens_df[movielens_df['SessionID'] == session_id].sort_values('Timestamp')
    item_sequence = session_data['MovieID'].tolist()
    plt.plot(range(len(item_sequence)), item_sequence, marker='o', label=f"Session {session_id}")

plt.title("🎞️ Item Interaction Trajectories within Sessions (MovieLens)")
plt.xlabel("Interaction Step")
plt.ylabel("Movie ID")
plt.legend()
plt.tight_layout()
plt.show()

import matplotlib.cm as cm

session_ids = movielens_df['SessionID'].dropna().unique()
session_lengths = movielens_df.groupby('SessionID').size()

# Plot top 10 longest sessions
top_sessions = session_lengths.sort_values(ascending=False).head(10).index
colors = cm.viridis(np.linspace(0, 1, len(top_sessions)))

plt.figure(figsize=(12, 6))

for i, session_id in enumerate(top_sessions):
    session_data = movielens_df[movielens_df['SessionID'] == session_id].sort_values('Timestamp')
    sequence = session_data['MovieID'].tolist()
    plt.plot(range(len(sequence)), sequence, label=f"Session {session_id}", color=colors[i], linewidth=2)

plt.title("🌈 Top 10 Longest Sessions - Item Interaction Paths")
plt.xlabel("Step in Session")
plt.ylabel("Movie ID")
plt.legend(loc='upper right')
plt.tight_layout()
plt.show()



"""#MODELING"""

!pip install -q kaggle torch scikit-learn pandas numpy tqdm matplotlib seaborn

import os
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import random

# ✅ GPU Setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Running on:", device)

# ✅ KAGGLE SETUP
from google.colab import files
files.upload()  # Upload your kaggle.json

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d fengzhujoey/douban-datasetratingreviewside-information -p /content
!unzip -q /content/douban-datasetratingreviewside-information.zip -d /content/douban
!wget https://files.grouplens.org/datasets/movielens/ml-1m.zip -O /content/ml-1m.zip
!unzip -q /content/ml-1m.zip -d /content/movielens

# ✅ LOAD AND PREPROCESS
movielens_df = pd.read_csv('/content/movielens/ml-1m/ratings.dat', sep='::', engine='python',
                           names=['UserID', 'MovieID', 'Rating', 'Timestamp'])
movielens_df['Timestamp'] = pd.to_datetime(movielens_df['Timestamp'], unit='s')
movielens_df = movielens_df.sort_values(['UserID', 'Timestamp'])

# ✅ Simulate sessions
def simulate_sessions_fast(df, user_col='UserID', time_col='Timestamp', gap_minutes=30):
    df = df.copy()
    df.sort_values(by=[user_col, time_col], inplace=True)
    df['TimeDiff'] = df.groupby(user_col)[time_col].diff().dt.total_seconds().div(60)
    df['NewSession'] = (df['TimeDiff'].isna()) | (df['TimeDiff'] > gap_minutes)
    df['SessionID'] = df.groupby(user_col)['NewSession'].cumsum()
    df.drop(columns=['TimeDiff', 'NewSession'], inplace=True)
    return df

movielens_df = simulate_sessions_fast(movielens_df)

# ✅ Save preprocessed
movielens_df.to_csv("/content/movielens_preprocessed.csv", index=False)

# ✅ RELOAD & MAP IDs
movielens_df = pd.read_csv('/content/movielens_preprocessed.csv')
movielens_df = movielens_df.dropna(subset=['SessionID', 'MovieID'])

# Remap MovieIDs to 0-based index
unique_ids = sorted(movielens_df['MovieID'].dropna().unique())
id_map = {old_id: new_id for new_id, old_id in enumerate(unique_ids)}
movielens_df['MappedMovieID'] = movielens_df['MovieID'].map(id_map).astype(int)

num_items = len(id_map)
print("Number of unique items:", num_items)

# ✅ LIMIT LONG SESSIONS
movielens_df = movielens_df.groupby("SessionID").head(20)

# ✅ SPLIT DATA
session_ids = movielens_df['SessionID'].unique()
np.random.seed(42)
np.random.shuffle(session_ids)
split_index = int(0.8 * len(session_ids))
train_sessions = session_ids[:split_index]
test_sessions = session_ids[split_index:]

train_df = movielens_df[movielens_df['SessionID'].isin(train_sessions)].copy()
test_df = movielens_df[movielens_df['SessionID'].isin(test_sessions)].copy()

# ✅ DATASET CLASS
class SequentialRecDataset(Dataset):
    def __init__(self, df, max_seq_len=20):
        self.user_sessions = []
        self.targets = []
        self.max_seq_len = max_seq_len

        for session_id, group in df.groupby("SessionID"):
            items = group["MappedMovieID"].tolist()
            if len(items) < 2:
                continue
            for i in range(1, len(items)):
                seq = items[:i]
                target = items[i]
                seq = ([0] * (max_seq_len - len(seq)) + seq)[-max_seq_len:]
                self.user_sessions.append(seq)
                self.targets.append(target)

    def __len__(self):
        return len(self.user_sessions)

    def __getitem__(self, idx):
        return torch.LongTensor(self.user_sessions[idx]), torch.LongTensor([self.targets[idx]])



class SessionEncoder(nn.Module):
    def __init__(self, num_items, embed_dim=64, hidden_dim=64):
        super().__init__()
        self.item_emb = nn.Embedding(num_items + 1, embed_dim, padding_idx=0)
        self.gru = nn.GRU(embed_dim, hidden_dim, batch_first=True)

    def forward(self, seq):
        x = self.item_emb(seq)  # (B, L, E)
        _, h_n = self.gru(x)    # (1, B, H)
        return h_n.squeeze(0)   # (B, H)

class UserEncoder(nn.Module):
    def __init__(self, num_items, d_model=64, max_seq_len=20):
        super().__init__()
        self.item_emb = nn.Embedding(num_items + 1, d_model, padding_idx=0)
        self.pos_emb = nn.Embedding(max_seq_len, d_model)
        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=2)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=1)

    def forward(self, seq):
        pos = torch.arange(seq.size(1), device=seq.device).unsqueeze(0).expand_as(seq)
        x = self.item_emb(seq) + self.pos_emb(pos)
        x = self.transformer(x.transpose(0, 1))  # (L, B, D)
        return x[-1]  # (B, D)

class DualEncoderRecModel(nn.Module):
    def __init__(self, num_items, hidden_dim=64, fusion='mlp'):
        super().__init__()
        self.session_encoder = SessionEncoder(num_items, hidden_dim, hidden_dim)
        self.user_encoder = UserEncoder(num_items, hidden_dim)
        self.fusion = fusion
        if fusion == 'mlp':
            self.fuse = nn.Sequential(
                nn.Linear(2 * hidden_dim, hidden_dim),
                nn.ReLU(),
                nn.Linear(hidden_dim, num_items + 1)
            )
        elif fusion == 'attention':
            self.attn = nn.MultiheadAttention(embed_dim=hidden_dim, num_heads=2, batch_first=True)
            self.out = nn.Linear(hidden_dim, num_items + 1)

    def forward(self, session_seq, user_seq=None):
        session_vec = self.session_encoder(session_seq)
        if user_seq is None:
            return self._predict_from(session_vec)

        user_vec = self.user_encoder(user_seq)

        if self.fusion == 'mlp':
            x = torch.cat([session_vec, user_vec], dim=-1)
            return self.fuse(x)
        elif self.fusion == 'attention':
            combined = torch.stack([session_vec, user_vec], dim=1)  # (B, 2, D)
            attn_output, _ = self.attn(combined, combined, combined)
            return self.out(attn_output[:, 0])

    def _predict_from(self, session_vec):
        return self.fuse(torch.cat([session_vec, torch.zeros_like(session_vec)], dim=-1))

# ✅ MODEL CLASS
class TransformerRecModel(nn.Module):
    def __init__(self, num_items, d_model=64, nhead=2, num_layers=1, max_seq_len=20):
        super().__init__()
        self.item_emb = nn.Embedding(num_items + 1, d_model, padding_idx=0)
        self.pos_emb = nn.Embedding(max_seq_len, d_model)
        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.out = nn.Linear(d_model, num_items + 1)

    def forward(self, seq):
        positions = torch.arange(seq.size(1), device=seq.device).unsqueeze(0).expand_as(seq)
        x = self.item_emb(seq) + self.pos_emb(positions)
        x = self.transformer(x.transpose(0, 1))  # (seq_len, batch, d_model)
        x = x[-1]  # Use last hidden state
        logits = self.out(x)
        return logits

# ✅ TRAINING FUNCTION
def train_model(model, train_loader, num_epochs=20, lr=0.001):
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0
        for seq, target in tqdm(train_loader):
            seq, target = seq.to(device), target.to(device).squeeze()
            optimizer.zero_grad()
            logits = model(seq)
            loss = criterion(logits, target)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f"Epoch {epoch+1}/{num_epochs} - Loss: {total_loss:.4f}")

# ✅ SETUP FOR TRAINING
BATCH_SIZE = 256
MAX_SEQ_LEN = 20

train_dataset = SequentialRecDataset(train_df, max_seq_len=MAX_SEQ_LEN)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)

model = TransformerRecModel(num_items=num_items, max_seq_len=MAX_SEQ_LEN)

# ✅ SANITY CHECK
assert train_df['MappedMovieID'].max() <= num_items

# ✅ TRAIN
train_model(model, train_loader, num_epochs=20, lr=0.001)



"""Phase 2"""

from sklearn.metrics import ndcg_score
import heapq

# ✅ Evaluation Dataset
class EvaluationDataset(Dataset):
    def __init__(self, df, max_seq_len=20):
        self.sequences = []
        self.targets = []
        self.max_seq_len = max_seq_len

        for session_id, group in df.groupby("SessionID"):
            items = group["MappedMovieID"].tolist()
            if len(items) < 2:
                continue
            seq = items[:-1]
            target = items[-1]
            seq = ([0] * (max_seq_len - len(seq)) + seq)[-max_seq_len:]
            self.sequences.append(seq)
            self.targets.append(target)

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        return torch.LongTensor(self.sequences[idx]), torch.LongTensor([self.targets[idx]])

# ✅ Evaluation Function
def evaluate_model(model, test_df, k=10):
    model.eval()
    eval_dataset = EvaluationDataset(test_df, max_seq_len=MAX_SEQ_LEN)
    eval_loader = DataLoader(eval_dataset, batch_size=64, num_workers=2, pin_memory=True)

    recall_total, ndcg_total = 0.0, 0.0
    count = 0

    with torch.no_grad():
        for seqs, targets in tqdm(eval_loader):
            seqs = seqs.to(device)
            targets = targets.to(device).squeeze()

            logits = model(seqs)  # (batch_size, num_items + 1)
            topk_preds = torch.topk(logits, k=k, dim=1).indices  # (batch_size, k)

            for i in range(seqs.size(0)):
                true_item = targets[i].item()
                predicted = topk_preds[i].tolist()

                # Recall@k
                if true_item in predicted:
                    recall_total += 1

                # NDCG@k
                relevance = [1 if item == true_item else 0 for item in predicted]
                ndcg_total += ndcg_score([relevance], [list(range(1, k + 1))])

                count += 1

    recall_at_k = recall_total / count
    ndcg_at_k = ndcg_total / count

    print(f"📈 Recall@{k}: {recall_at_k:.4f}")
    print(f"📈 NDCG@{k}: {ndcg_at_k:.4f}")

evaluate_model(model, test_df, k=10)

def recommend_next(model, session_items, id_map, max_seq_len=20, top_k=5):
    model.eval()
    reverse_id_map = {v: k for k, v in id_map.items()}

    # Prepare sequence
    mapped_seq = [id_map[item] for item in session_items if item in id_map]
    mapped_seq = ([0] * (max_seq_len - len(mapped_seq)) + mapped_seq)[-max_seq_len:]
    input_tensor = torch.LongTensor(mapped_seq).unsqueeze(0).to(device)

    with torch.no_grad():
        logits = model(input_tensor)
        topk = torch.topk(logits, k=top_k, dim=1).indices.squeeze().tolist()

    return [reverse_id_map[idx] for idx in topk if idx in reverse_id_map]

# Suppose this user watched these MovieIDs
example_session = [1193, 661, 914]  # real MovieLens IDs
recommend_next(model, example_session, id_map, top_k=5)

"""# Add Douban Social Signal to Transformer Model

Parse Douban User-User Connections
python
Copy code
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load raw users file
douban_users_path = "/content/douban/douban_dataset(text information)/users_cleaned.txt"
raw_users_df = pd.read_csv(douban_users_path, sep="\t", header=None, engine="python", quoting=3, on_bad_lines='skip')

# Drop rows with nulls and select only first 2 columns
raw_users_df = raw_users_df.dropna().iloc[:, :2]
raw_users_df.columns = ['UserID', 'FriendID']

# Filter out rows with obvious non-user strings (like 'living_place', 'gender', etc.)
def is_valid_user(x):
    return isinstance(x, str) and len(x) < 100 and 'place' not in x.lower() and 'gender' not in x.lower()

filtered_users_df = raw_users_df[
    raw_users_df['UserID'].apply(is_valid_user) & raw_users_df['FriendID'].apply(is_valid_user)
]

# Encode user IDs to indices
user_encoder = LabelEncoder()
all_users = pd.concat([filtered_users_df['UserID'], filtered_users_df['FriendID']])
user_encoder.fit(all_users)

filtered_users_df['UserIndex'] = user_encoder.transform(filtered_users_df['UserID'])
filtered_users_df['FriendIndex'] = user_encoder.transform(filtered_users_df['FriendID'])

num_users = max(filtered_users_df['UserIndex'].max(), filtered_users_df['FriendIndex'].max()) + 1

"""Build User Graph + Generate Social Embeddings"""

import networkx as nx
import torch

# Build graph
G = nx.Graph()
G.add_edges_from(filtered_users_df[['UserIndex', 'FriendIndex']].values)


# Simple node degree as 1D social embedding
social_features = torch.zeros(num_users, 1)
for u, d in dict(G.degree()).items():
    social_features[u] = d

# Normalize
social_features = (social_features - social_features.mean()) / social_features.std()

"""Create Dataset with Social Info (for MovieLens)
python
Copy code

"""

from torch.utils.data import Dataset

class SocialRecDataset(Dataset):
    def __init__(self, df, user_map, max_seq_len=20):
        self.user_sessions = []
        self.targets = []
        self.social_indices = []
        self.max_seq_len = max_seq_len

        for session_id, group in df.groupby("SessionID"):
            items = group["MappedMovieID"].tolist()
            users = group["UserID"].tolist()
            if len(items) < 2:
                continue
            for i in range(1, len(items)):
                seq = items[:i]
                target = items[i]
                user = users[i]
                seq = ([0] * (max_seq_len - len(seq)) + seq)[-max_seq_len:]
                self.user_sessions.append(seq)
                self.targets.append(target)
                self.social_indices.append(user_map.get(user, 0))  # default index 0

    def __len__(self):
        return len(self.user_sessions)

    def __getitem__(self, idx):
        return (
            torch.LongTensor(self.user_sessions[idx]),
            torch.LongTensor([self.targets[idx]]),
            torch.LongTensor([self.social_indices[idx]])
        )

"""
Social-Aware Transformer Model"""

import torch.nn as nn

class SocialTransformerRecModel(nn.Module):
    def __init__(self, num_items, social_dim=1, d_model=128, nhead=4, num_layers=2, max_seq_len=20):
        super().__init__()
        self.item_emb = nn.Embedding(num_items + 1, d_model, padding_idx=0)
        self.pos_emb = nn.Embedding(max_seq_len, d_model)
        self.social_proj = nn.Linear(social_dim, d_model)
        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.out = nn.Linear(d_model, num_items + 1)

    def forward(self, seq, social_vec):
        pos = torch.arange(seq.size(1), device=seq.device).unsqueeze(0)
        x = self.item_emb(seq) + self.pos_emb(pos)
        social_embed = self.social_proj(social_vec).unsqueeze(1)
        x = x + social_embed  # broadcast across sequence
        x = self.transformer(x.transpose(0, 1))  # Transformer expects (seq_len, batch, dim)
        x = x[-1]  # use last token
        logits = self.out(x)
        return logits

"""Train with Social Context"""

from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch.optim as optim
from tqdm import tqdm

def train_social_model(model, train_loader, social_features, num_epochs=5, lr=0.001, device='cuda' if torch.cuda.is_available() else 'cpu'):
    model.to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0
        for seq, target, social_idx in tqdm(train_loader):
            seq = seq.to(device)
            target = target.squeeze().to(device)
            social_idx = social_idx.squeeze().to(device)
            social_vec = social_features[social_idx].to(device)

            optimizer.zero_grad()
            logits = model(seq, social_vec)
            loss = criterion(logits, target)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f"Epoch {epoch+1}/{num_epochs} - Loss: {total_loss:.4f}")

"""Plug It Together"""

# Map MovieLens UserID to Douban UserIndex
user_map = {uid: user_encoder.transform([uid])[0] if uid in user_encoder.classes_ else 0
            for uid in train_df['UserID'].unique()}

# Dataset + Loader
train_dataset_social = SocialRecDataset(train_df, user_map)
train_loader_social = DataLoader(train_dataset_social, batch_size=64, shuffle=True)

# Model
model_social = SocialTransformerRecModel(num_items=num_items)

# Train!
train_social_model(model_social, train_loader_social, social_features)

"""#Re-evaluate"""

import numpy as np

def recall_at_k(preds, targets, k):
    """Computes Recall@K"""
    recall = 0.0
    for p, t in zip(preds, targets):
        recall += int(t in p[:k])
    return recall / len(preds)

def ndcg_at_k(preds, targets, k):
    """Computes NDCG@K"""
    ndcg = 0.0
    for p, t in zip(preds, targets):
        if t in p[:k]:
            idx = p.index(t)
            ndcg += 1 / np.log2(idx + 2)
    return ndcg / len(preds)

"""Evaluation Function (Both Models)
python
Copy code

"""

def evaluate_model(model, dataloader, social_features=None, k=10, device='cuda' if torch.cuda.is_available() else 'cpu'):
    model.eval()
    model.to(device)
    preds, targets = [], []

    with torch.no_grad():
        for seq, target, *social_idx in dataloader:
            seq = seq.to(device)
            target = target.squeeze().to(device)

            if social_features is not None:
                social_idx = social_idx[0].squeeze().to(device)
                social_vec = social_features[social_idx].to(device)
                logits = model(seq, social_vec)
            else:
                logits = model(seq)

            top_k = torch.topk(logits, k=k, dim=1).indices.tolist()
            preds.extend(top_k)
            targets.extend(target.tolist())

    recall = recall_at_k(preds, targets, k)
    ndcg = ndcg_at_k(preds, targets, k)
    return recall, ndcg

"""Evaluate Both Models"""

movielens_df = pd.read_csv('/content/movielens_preprocessed.csv')

# Label encode ItemID
item_encoder = LabelEncoder()
movielens_df['MappedMovieID'] = item_encoder.fit_transform(movielens_df['MovieID'])

# Train-test split by SessionID
session_ids = movielens_df['SessionID'].unique()
np.random.shuffle(session_ids)
split_point = int(len(session_ids) * 0.8)
train_sessions = session_ids[:split_point]
test_sessions = session_ids[split_point:]

train_df = movielens_df[movielens_df['SessionID'].isin(train_sessions)]
test_df = movielens_df[movielens_df['SessionID'].isin(test_sessions)]

class RecDataset(Dataset):
    def __init__(self, df, max_seq_len=20):
        self.sequences = []
        self.targets = []
        grouped = df.groupby("SessionID")
        for _, group in grouped:
            items = group["MappedMovieID"].tolist()
            if len(items) < 2:
                continue
            for i in range(1, len(items)):
                seq = items[:i]
                target = items[i]
                seq = ([0] * (max_seq_len - len(seq)) + seq)[-max_seq_len:]
                self.sequences.append(seq)
                self.targets.append(target)

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        return (
            torch.LongTensor(self.sequences[idx]),
            torch.LongTensor([self.targets[idx]])
        )

# Create Datasets
train_dataset = RecDataset(train_df)
test_dataset = RecDataset(test_df)

# Dataloaders for Baseline
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64)

# Reuse same user_map from training step
test_dataset_social = SocialRecDataset(test_df, user_map)
test_loader_social = DataLoader(test_dataset_social, batch_size=64)

# 🍃 Baseline Transformer (no social)
recall_base, ndcg_base = evaluate_model(model, test_loader, k=10)

# 👥 Social-Aware Transformer
recall_social, ndcg_social = evaluate_model(model_social, test_loader_social, social_features=social_features, k=10)

print(f"🎯 Baseline - Recall@10: {recall_base:.4f}, NDCG@10: {ndcg_base:.4f}")
print(f"🎯 Social   - Recall@10: {recall_social:.4f}, NDCG@10: {ndcg_social:.4f}")

"""Visualize Gains"""

import matplotlib.pyplot as plt

# Metric values
metrics = ['Recall@10', 'NDCG@10']
baseline_scores = [recall_base, ndcg_base]
social_scores = [recall_social, ndcg_social]
improvement = [(s - b) * 100 / b for s, b in zip(social_scores, baseline_scores)]

# Plot scores
plt.figure(figsize=(10, 5))
x = np.arange(len(metrics))
bar_width = 0.35

plt.bar(x - bar_width/2, baseline_scores, bar_width, label='Baseline')
plt.bar(x + bar_width/2, social_scores, bar_width, label='Social-Aware', color='mediumseagreen')
plt.xticks(x, metrics)
plt.ylabel("Score")
plt.title("Model Comparison: Baseline vs Social-Aware")
plt.legend()
plt.tight_layout()
plt.show()

# Plot improvement %
plt.figure(figsize=(7, 4))
plt.bar(metrics, improvement, color='salmon')
plt.ylabel("Improvement (%)")
plt.title("🔼 % Gain with Social Signals")
for i, val in enumerate(improvement):
    plt.text(i, val + 0.2, f"{val:.2f}%", ha='center')
plt.tight_layout()
plt.show()







